### ISSUE TITLE
Can I get the code of 《Learning Better Sentence Representation with Syntax Information》

### ISSUE THREAD

**Issue by tongbc** [cyang-cityu/cyang.github.io#1]
您好，请问我能否看一下《Learning Better Sentence Representation with Syntax Information》的代码，或者能否帮忙解释一下，因为预训练模型会通过BPE将一个词语分成一个或者多个部分，当分成多个部分时，请问如何像文章中将word, parent, relation 对应上呢，我尝试复现但是一直没有想通这个问题，如果可以的话，能否向您请教一下，我的邮箱是tongbaichen@tal.com，非常感谢您~

**Comment by cyang-cityu** [comment]
你好,我不是这篇论文《Learning Better Sentence Representation with Syntax Information》的作者,只是巧合重名了...

**Comment by tongbc** [comment]
> 你好,我不是这篇论文《Learning Better Sentence Representation with Syntax Information》的作者,只是巧合重名了...

好的。。不好意思拉~
